// This file is autogenerated. Changes will be overwritten.
#include "UVLADIE3JM/moc_ChannelPointPlugin.cpp"
#include "L3BDCI33OQ/moc_AnalyticsManager.cpp"
#include "L3BDCI33OQ/moc_EffectManager.cpp"
#include "L3BDCI33OQ/moc_ObsNotifier.cpp"
#include "L3BDCI33OQ/moc_QueueManager.cpp"
#include "YPKJ5OE7LN/moc_PluginMainWidget.cpp"
#include "YPKJ5OE7LN/moc_VisualPreviewWidget.cpp"
